### ISSUE TITLE
Unable to reset API user / key

### ISSUE THREAD

**Issue by johavik** [MvdDonk/brewfather#20]
Hi!

I've renewed the Brewfather API user / key. I get a 401 error from the integration, but I'm unable to configure new credentials.
Redownloading the integration does not help.

**Comment by MvdDonk** [comment]
Hi @johavik ,

thanks for reporting the issue. Does it happen to an existing connection/integration? So this happend after you first  sucessfully have setup Brewfather integration?
The easiest way to fix this (at this moment) is to remove the current connection by going to [Brewfather ](https://my.home-assistant.io/redirect/integration/?domain=brewfather) and by clicking delete:

![image](https://github.com/user-attachments/assets/17f5f0ad-d1a0-4adc-b6b4-767fe9b51f61)

After that you can create a new connection and enter the correct credentials:
![image](https://github.com/user-attachments/assets/1e0d8fa7-75f8-488d-bf13-9f5d82253322)
![image](https://github.com/user-attachments/assets/2547a8f4-f2fe-448b-b988-6953fe7ed0c9)

Hopefully this works for you, if not let me know.

**Comment by johavik** [comment]
Thanks for getting back to me.

Deleting and re-adding works, but now any change in the configuration settings will mess up the authentication. Steps to reproduce:

1. Delete the connection
2. Re-add the connection
3.  Everything works fine at this point. The integration pulls data from Brewfather.
4. Open the configuration and click submit (it's not necessary to make any changes)
6. The integration fails to connect after saving changes to the configuration:
![image](https://github.com/user-attachments/assets/5def10d8-780c-4743-aa08-a22a6022f3fd)

From the log:

2024-12-30 15:27:24.468 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry brewfather for brewfather
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/brewfather/__init__.py", line 28, in async_setup_entry
    coordinator = BrewfatherCoordinator(hass, config_entry, update_interval)
  File "/config/custom_components/brewfather/coordinator.py", line 70, in __init__
    self.connection = Connection(
                      ~~~~~~~~~~^
        entry.data.get(CONF_USERNAME, 'no-username-found-in-config'),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        entry.data.get(CONF_PASSWORD, 'no-password-found-in-config')
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/config/custom_components/brewfather/connection.py", line 35, in __init__
    self.auth = aiohttp.BasicAuth(username, apikey)
                ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/helpers.py", line 129, in __new__
    raise ValueError("None is not allowed as login value")
ValueError: None is not allowed as login value


There is no urgency to this, I'll try to look into the home assistant reauth flow.

**Comment by MvdDonk** [comment]
@johavik it is really weird, somehow it seems that the config (username and api code) are lost in the middle of things... It seems it's trying to authenticate with username "None" which happens if the config data is empty in Home Assistant...
Even more weird is that apperently the config object exists but the actual value of the Username is "None".
If just tested it on my testing machine and live and both didn't have this problem. How are  you running Home Assistant and which version are you using (both of Home Assistant and Brewfather)?

**Comment by johavik** [comment]
@MvdDonk, I just did a new install of HA, HACS and your integration. **Deleting and recreating the connection works fine** :)

Probably time for some housekeeping, my HA instance is up to date but has been upgraded over and over for a very long time.
