### ISSUE TITLE
Failed to set up

### ISSUE THREAD

**Issue by ce-designs** [MvdDonk/brewfather#9]
I tried to install your implementation of brewfather by copying the entire brewfather folder to the custom_components  folder. 
After restarting it finds the brewfather integration, but it fails to set up after entering my user-ID and API-key.

In the debug log file I can see the JSON strings with my recipies, so the connection to BF succeeded. It doesn't seem to be able to setup the device or entities. Any idea on how to solve this?

HA version: Docker
Core: 2023.11.2
Frontend: 20231030.2

![image](https://github.com/MvdDonk/brewfather/assets/7289338/4d7f3457-a67a-4612-88bd-e11b2ac96be7)
[home-assistant_brewfather_2023-11-20T18-24-00.924Z.log](https://github.com/MvdDonk/brewfather/files/13418286/home-assistant_brewfather_2023-11-20T18-24-00.924Z.log)

**Comment by MvdDonk** [comment]
Thanks for the log file. I'll have a look at the issue asap.

**Comment by MvdDonk** [comment]
Hi @ce-designs , could you update to version v1.1.5 and check if it's working again? Thanks

**Comment by ce-designs** [comment]
Sure! I'll test it asap and let you know the results.

**Comment by ce-designs** [comment]
It works now, but there's an bug in your logica.

Line 332 in file: custom_components/brewfather/models/batch_item.py

`if self.readings is not None and len(self.readings) > 0:
            result["current_temperature"] = self.readings[0].temp
        else:
            result["current_temperature"] = None`

Looks like the first index of readings contains the first temperature reading instead of the last. You should probably get the last item from the array, assuming that the readings are ordered ascending by date.

The BF API also contains a call for retrieving the last reading. It might be safer and more efficient to use this call.

/v2/batches/:batch_id/readings/last

**Comment by MvdDonk** [comment]
Hi @ce-designs thanks for letting me know. You are probably correct that using readings/last would be better. But since I don't have that much time available I choose to just order the readings in code by sorting them based on the time property. 
I posted a update: v1.1.6

**Comment by ce-designs** [comment]
This should also work!

 I can relate to you about not having much time, so when I have some time then I can try to make a change for using the readings/last call and create a pull request...

**Comment by MvdDonk** [comment]
@ce-designs ah that would be great 👍! 
Can you confirm the new version fixes the initial bug you reported? That way I can close the story.
